on:
  pull_request: {}
  push:
    branches:
    - main
    - master
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:
name: Semgrep
jobs:
  semgrep:
    name: Scan
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: returntocorp/semgrep-action@v1
      with:
        auditOn: push
        publishToken: ${{ secrets.SEMGREP_APP_TOKEN }}
  metrics:
    needs: [semgrep]
    runs-on: ubuntu-latest
    name: Report logs to datadog
    if: ${{ always() }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Install dependencies
        run: python -m pip install PyGithub requests
      - name: send metrics
        run: python send_to_datadog.py ${{github.run_id}}
        env:
          DD_API_KEY: ${{ secrets.DD_API_KEY }}
